baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'FRC Team 4533'
enablerobotstxt = true
timezone = "America/New_York"
copyright = "© Phoenix 2024"

[[module.imports]]
path = 'github.com/willfaught/paige'

[params.paige]
site_title = "4533 Phoenix"
site_description = "FRC Team 4533 - Mount Pleasant, SC"

[paige.menu]
style = 'links'

[paige.search]
hide_page = true

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 20

[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 30

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 40

[languages.en.menu.main.params.paige]
divider_below = true
disabled = false

[markup.goldmark.renderer]
unsafe = true

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2
