baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'FRC Team 4533'

[[module.imports]]
path = 'github.com/willfaught/paige'

[params.paige]
site_title = "4533 Phoenix"
site_description = "FRC Team 4533 - Mount Pleasant, SC"

[paige.menu]
style = 'links'

[paige.search]
hide_page = false

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "about"
name = "About us"
url = "/about"
weight = 20

[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 30

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 40

[[languages.en.menu.main]]
identifier = "github"
name = "Github"
url = "/github"
weight = 50

[languages.en.menu.main.params.paige]
divider_below = true
disabled = false

[markup.goldmark.renderer]
unsafe = true
